<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-15T10:49:04 IST" name="All Test Suite" finished-at="2023-09-15T10:49:42 IST" duration-ms="37919">
    <groups>
      <group name="Purchase">
        <method signature="StandaloneTest.submitOrder(java.util.HashMap)[pri:0, instance:StandaloneTest@5524cca1]" name="submitOrder" class="StandaloneTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-09-15T10:49:04 IST" name="Error Validation Test" finished-at="2023-09-15T10:49:04 IST" duration-ms="16">
    </test> <!-- Error Validation Test -->
    <test started-at="2023-09-15T10:49:04 IST" name="Submit Order Test" finished-at="2023-09-15T10:49:42 IST" duration-ms="37919">
      <class name="StandaloneTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:04 IST" name="launchApplication" finished-at="2023-09-15T10:49:14 IST" duration-ms="9761" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:14 IST" name="LoginErrorValidation" finished-at="2023-09-15T10:49:15 IST" duration-ms="769" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:15 IST" name="tearDown" finished-at="2023-09-15T10:49:15 IST" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:15 IST" name="launchApplication" finished-at="2023-09-15T10:49:17 IST" duration-ms="1806" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:17 IST" name="submitOrder" data-provider="getData" finished-at="2023-09-15T10:49:25 IST" duration-ms="8115" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Abcd@1234, username=aman1512@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:25 IST" name="tearDown" finished-at="2023-09-15T10:49:25 IST" duration-ms="122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:25 IST" name="launchApplication" finished-at="2023-09-15T10:49:28 IST" duration-ms="2358" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:28 IST" name="submitOrder" data-provider="getData" finished-at="2023-09-15T10:49:36 IST" duration-ms="8134" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=India@2015, username=tariqrasheed1989@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:36 IST" name="tearDown" finished-at="2023-09-15T10:49:36 IST" duration-ms="126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:36 IST" name="launchApplication" finished-at="2023-09-15T10:49:38 IST" duration-ms="1956" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="OrderHistoryTest()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:38 IST" name="OrderHistoryTest" finished-at="2023-09-15T10:49:39 IST" depends-on-methods="StandaloneTest.submitOrder" duration-ms="866" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at StandaloneTest.OrderHistoryTest(StandaloneTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:39 IST" name="tearDown" finished-at="2023-09-15T10:49:39 IST" duration-ms="64" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:39 IST" name="launchApplication" finished-at="2023-09-15T10:49:41 IST" duration-ms="1921" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:41 IST" name="OrderHistoryTest" finished-at="2023-09-15T10:49:42 IST" depends-on-methods="StandaloneTest.submitOrder" duration-ms="912" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at StandaloneTest.OrderHistoryTest(StandaloneTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:StandaloneTest@5524cca1]" started-at="2023-09-15T10:49:42 IST" name="tearDown" finished-at="2023-09-15T10:49:42 IST" duration-ms="132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- StandaloneTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- All Test Suite -->
</testng-results>
